api_json:
  - nome: "PNCP (Licitações)"
    url: "https://pncp.gov.br/api/consulta/v1/contratacoes/publicacao?dataInicial={ha30dias}&dataFinal={hoje}&codigoModalidadeContratacao={variacao}&codigoMunicipioIbge=3545803&pagina=1&tamanhoPagina=50"
    variacoes: [6, 8, 9, 4]
    campos:
      id: "numeroControlePNCP"
      titulo: "objetoCompra"
      data: "dataPublicacaoPncp"
      link: "linkSistemaOrigem"

  - nome: "PNCP (Contratos)"
    url: "https://pncp.gov.br/api/consulta/v1/contratos?dataInicial={ha30dias}&dataFinal={hoje}&cnpjOrgao=46422408000152&pagina=1&tamanhoPagina=50"
    campos:
      id: "numeroControlePNCP"
      titulo: "objetoContrato"
      data: "dataPublicacaoPncp"
      valor: "valorInicial"

  - nome: "Diário Oficial de SBO"
    url: "https://www.santabarbara.sp.gov.br/portal/dados-abertos/diario-oficial/{ano}"
    campos:
      id: "edicao"
      titulo: "descricao"
      data: "data"

  - nome: "TCE-SP (Despesas)"
    url: "https://transparencia.tce.sp.gov.br/api/json/despesas/santa-barbara-d-oeste/{ano}/{mes}"
    campos:
      id: "nr_empenho"
      titulo: "nm_fornecedor"
      data: "dt_emissao_despesa"
      valor: "vl_despesa"

html:
  - nome: "Câmara de SBO (Sessões)"
    url: "https://santabarbara.siscam.com.br/sessoes"
    selector: ".table-responsive table tbody tr td a"
    base: "https://santabarbara.siscam.com.br"
